# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pradeep/work/mylayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_predictionmodel(object):
    def setupUi(self, predictionmodel):
        predictionmodel.setObjectName("predictionmodel")
        predictionmodel.resize(600, 400)
        predictionmodel.setWindowOpacity(0.5)
        predictionmodel.setStyleSheet("background-color: rgb(117, 80, 123);")
        predictionmodel.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(predictionmodel)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 181, 58))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setMinimumSize(QtCore.QSize(179, 0))
        self.pushButton_2.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setSizeIncrement(QtCore.QSize(100, 100))
        self.pushButton.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        predictionmodel.setCentralWidget(self.centralwidget)

        self.retranslateUi(predictionmodel)
        QtCore.QMetaObject.connectSlotsByName(predictionmodel)

    def retranslateUi(self, predictionmodel):
        _translate = QtCore.QCoreApplication.translate
        predictionmodel.setWindowTitle(_translate("predictionmodel", "Prediction Model"))
        self.pushButton_2.setText(_translate("predictionmodel", "Classification"))
        self.pushButton.setText(_translate("predictionmodel", "Regression"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    predictionmodel = QtWidgets.QMainWindow()
    ui = Ui_predictionmodel()
    ui.setupUi(predictionmodel)
    predictionmodel.show()
    sys.exit(app.exec_())
